# v1 or v2 specific sections are omitted.
x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "3.6.2"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false

  images: {}

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  installSpinnaker:
    type: boolean
    title: To Install Spinnaker
    description: To enable or disable  Spinnaker installation along with OES
    default: true
  global.spinDeck.host:
    type: string
    title: Spinnaker Deck Host URL
    pattern: '^(([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
    default: spin-gcp.opsmx.com
  global.spinGate.host:
    type: string
    title: Spinnaker Gate Host URL
    pattern: '^(([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
    default: spin-gate-gcp.opsmx.com
  oesUI.host:
    type: string
    title: Spinnaker Gate Host URL
    pattern: '^(([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
    default: oes-gcp.opsmx.com
  oesGate.host:
    type: string
    title: Spinnaker Gate Host URL
    pattern: '^(([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'
    default: oes-gate-gcp.opsmx.com
required:
- name
- namespace
- installSpinnaker
- global.spinDeck.host
- global.spinGate.host
- oesUI.host
- oesGate.host
