apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}    --- Place the Logo file (OR) https://www.opsmx.com/images/logo.png
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "opsmx", "product_id": "OES", "partner_name": "OpsMx"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: OES
    version: '3.6.2'
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: apps/v1
    kind: StatefulSet
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
  - group: apps/v1
    kind: Deployment
  - group: extensions/v1beta1
    kind: Ingress
